apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::101553892293:role/eksctl-my-eks-cluster-nodegroup-ap-NodeInstanceRole-B5kcChClq60O
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
    - rolearn: arn:aws:iam::101553892293:role/GitHubActions-ECR-EKS-Role
      groups:
      - system:masters
      username: github-actions